# Generated by Django 4.2.6 on 2023-10-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_idea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Idea',
        ),
    ]
