# Generated by Django 4.2.6 on 2023-10-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='time',
            new_name='pub_date',
        ),
    ]
